hyperlane-xyz/hyperlane-explorer

- src/features/messages/queries/useMessageQuery.ts
Increased the limit to 30 which imo looks better and also should not actually. have a performance hit?
> Increase message query limit to 30

- src/features/debugger/debugMessage.ts
- src/features/debugger/types.ts
- src/features/messages/cards/TransactionCard.tsx
So that you can actually simulate
> Add Mailbox to Tenderly card

- src/consts/environments.ts
Noticed we were still using version `0` in the raw bytes when I tried copying it from the explorer
> Use mailbox version 3

- package.json
- src/components/icons/HelpIcon.tsx
- src/pages/_app.tsx
- yarn.lock
We should use tooltips to display tip information instead of Toasts.
**Reasons:**
- Users have to shift their focus from the current help area to the bottom right corner, resulting in poor user experience. It becomes unclear which help was hovered over after moving the mouse.
- Toasts have a delay that is too long and are limited to a maximum of two. Even when moving to another location or page, they still appear and continue to display if clicked multiple times.
**Solution:**
- Implement tooltips using [react-tooltip](https://react-tooltip.com/docs/getting-started).
- Remove the onClick event and display tooltips instead of Toasts.
I have some demo videos here:
Before:
https://github.com/hyperlane-xyz/hyperlane-explorer/assets/15717476/67bc4d5a-c29f-4fb8-9a09-a96640b66da0
After: …
> fix: replace use tooltip instead of toast for show tip information

- package.json
- src/components/layout/AppLayout.tsx
- src/components/search/SearchFilterBar.tsx
- src/components/search/SearchStates.tsx
- src/features/chains/ConfigureChains.tsx
- src/features/chains/utils.ts
- src/features/debugger/debugMessage.ts
- src/features/deliveryStatus/fetchDeliveryStatus.ts
- src/features/deliveryStatus/useMessageDeliveryStatus.tsx
- src/features/messages/MessageDetails.tsx
- src/features/messages/MessageSearch.tsx
- src/features/messages/MessageTable.tsx
- src/features/messages/cards/ContentDetailsCard.tsx
- src/features/messages/cards/TransactionCard.tsx
- src/features/messages/ica.ts
- src/features/messages/pi-queries/usePiChainMessageQuery.ts
- src/features/messages/queries/parse.ts
- src/features/messages/queries/useMessageQuery.ts
- src/pages/_app.tsx
- src/store.ts
- yarn.lock
**Builds on https://github.com/hyperlane-xyz/hyperlane-explorer/pull/72**
- Fix problems with delivery checking
- Remove status badge from message table
- Update react-query lib
- Remove unused, outdated wagmi + rainbowkit libs
- Fix error when filtering to all mainnets
- Avoid misleading status check for non-evm chains
- Hide v2 link banner
Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2122
Fixes https://github.com/hyperlane-xyz/issues/issues/735
Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3641
Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3668
> Various post-registry explorer fixes

- src/components/search/SearchFilterBar.tsx
Add wrong query chainId when search 
Issue: https://github.com/hyperlane-xyz/hyperlane-explorer/issues/91
Return only evm chain with bigint type not string
```diff
-  return { chains, mainnets, testnets };
+  // Return only evnChains because of graphql only accept query non-evm chains (with bigint type not string)
+  return { chains: coreEvmChains, mainnets, testnets };
```
> fix: error query with non-evm chainId when search

- src/components/search/SearchFilterBar.tsx
feat: scrollable search filter
much needed now that our set of supported chains is taller than a vertical monitor
> feat: scrollable search filter

- src/components/nav/Header.tsx
- src/features/messages/MessageDetails.tsx
- src/features/messages/cards/TransactionCard.tsx
- src/types.ts
- src/utils/time.ts
- Display duration in dest tx card per request from @Skunkchain 
- Display mailbox address in both tx cards
- Hide API docs page link which was disabled in #77 
- Fix missing type annotation
> feat: Add information to msg transaction cards

- src/components/nav/Header.tsx
- src/utils/browser.ts
- src/utils/useScrollListener.ts
Fixed an issue where on some specific threshold it would cause the header to loop the scaling animation because of the height changes. Move timeoutId so the variable is not re-created everytime and added a missing logic that would prevent proper debouncing
Caveat: If the scroll is extremely fast it might cause the header to be stuck on a certain threshold until a new scroll happens
Fixed an issue with `Firefox` choppy and slow animation, basically some browsers struggle with animation because of the way they render a page, so the "trick" is to make the browser go into hardware acceleration mode by adding a slight `rotation` and this way the animations will run smoother
On Firefox if you pay really close attention there's still a bit of a delay/blurriness that is almost not noticeable when …
> fix: header scroll looping and firefox slow animation

- package.json
- src/components/icons/ChainLogo.tsx
- src/components/search/SearchFilterBar.tsx
- src/features/chains/MissingChainConfigToast.tsx
- src/features/chains/queries/useScrapedChains.ts
- src/features/chains/utils.ts
- src/features/deliveryStatus/fetchDeliveryStatus.ts
- src/features/deliveryStatus/useMessageDeliveryStatus.tsx
- src/features/messages/MessageDetails.tsx
- src/features/messages/MessageTable.tsx
- src/features/messages/cards/GasDetailsCard.tsx
- src/features/messages/cards/TransactionCard.tsx
- src/features/messages/pi-queries/fetchPiChainMessages.ts
- src/features/messages/pi-queries/usePiChainMessageQuery.ts
- src/features/messages/queries/parse.ts
- src/utils/explorers.ts
- yarn.lock
relates to:
- https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/313
- https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4798
testing:
> feat: use chain name or domain as identifier instead of chainId 

- src/features/deliveryStatus/fetchDeliveryStatus.ts
- src/features/messages/MessageDetails.tsx
- src/features/messages/MessageTable.tsx
use tryGetChainName instead of hard crashing for unknown domains
tested locally
> fix: tryGetChainName instead of hard crashing

- src/features/messages/cards/GasDetailsCard.tsx
This PR fixes [Issue #129](https://github.com/hyperlane-xyz/hyperlane-explorer/issues/129) by setting the initial display to use the correct native token decimals in GasDetailsCard. This ensures accurate Total paid values are shown in the explorer.
> Fix Initial Decimal Display Issue and Improve Gas Payment Formatting in Hyperlane Explorer

- src/components/search/SearchFilterBar.tsx
- src/components/search/SearchStates.tsx
- src/features/messages/MessageSearch.tsx
- src/features/messages/queries/useMessageQuery.ts
- src/utils/queryParams.ts
fixes #145 
- Chain picker and time picker will now sync with the URL. 
- Navigation to this URL will make it so that these filters will remain and be sent to the message query
- For the chains, the keys are `origin` and `destination` and their value will be a `domainId`. Inputting an invalid `domainId` will prompt the `SearchChainError` component to show
- For the time, the keys are `startTime` and `endTime` and their value is a number. The initial load of the values are validated by the function `tryToDecimalNumber()`
- Refactor functions to allow multiple query params.
> feat: sync url with filters

- src/features/debugger/debugMessage.ts
fixes #150 
- Now runs `tryCheckBytecodeHandle` only for real contracts
- Checks if given contract is a proxy, if it is try to get proxy implementation contract
- When an `proxyImplementationContract` is returned runs `bytecode` check for it, otherwise just runs `bytecode` check for the recipient
> feat: run checkBytecodeHandle on proxy implementation contract in debugMessage

- src/features/messages/MessageTable.tsx
Fixed an issue that caused the icons to not show for mobile screens
- The culprit is the `absolute` position on the icon span, that anchors to the main table `relative` (Kinda weird that it worked before). All the icons would absolute position to the center of the table
- Removed `absolute` position on the icon, added a small width to the `LinkCell` so that it can display the icon
> fix: status icon not showing on mobile

- src/consts/config.ts
Same fix as #149, add Treasure Topaz Testnet to debug ignored chain until further notice
> chore: add treasuretopaz to debug ignored chains

- src/components/search/SearchFilterBar.tsx
- src/features/messages/MessageSearch.tsx
- src/features/messages/queries/build.ts
- src/features/messages/queries/useMessageQuery.ts
Now uses chain name instead of `domainId` as URL filter
- Update `ChainSelector` onChange function to update value with chain name instead of `domainId`
- Update logic for `useMessageSearchQuery` to get `domainId` from chain name 
fixes #170
> feat: use chain name instead of domainId for filters

- src/features/chains/utils.ts
fix: correctly return chain display name
- we were previously converting all names `toTitleCase`, when we only need to do that if we fallback to the standard chain name
- displayName / displayNameShort should be displayed as-is
before:
after:
> fix: correctly return chain display name

- src/features/debugger/debugMessage.ts
Increase delay before checking for IGP payment to 60 seconds
> chore: increase igp check delay

- src/features/messages/cards/WarpTransferDetailsCard.tsx
Fixed an issue where some warp routes had different decimals, which caused the amount field to display incorrectly because it used origin decimals instead, currently we don't have a great way of representing remote decimals but using the max between the chains in the warp route would proof mostly correct (not guaranteed)
before:
after:
> fix: decimals amount for warp transfer detail cards

- src/pages/api-docs.tsx
Now returns 404 page for` /api-docs` route
> chore: return not found for api-docs

- package.json
- src/features/messages/queries/build.ts
- src/features/messages/queries/useMessageQuery.ts
close #195 
- Remove testnet message by default
- Now origin and destination will filter by mainnet chains if no filters are provided
- Bump `package.json` version in accordance to `hyperlane` packages upgrade
Running the queries locally show that they still get result very fast regardless of the amount of chains set (around 130 for both origin and destination)
Speed seems to run between: 90 ~ 360ms, where the highest spike occurs when the query is first fetched or if there hasn't been a refetch in a while, in comparison to the current production build where query last around 90~200ms
> feat: filter out testnet messages by default

- package.json
- yarn.lock
Bumps the registry package version to enable parsing of new warp routes on the ui
> chore: bump registry package version

- src/store.ts
Now safeParse each chain before building multiProvider, this will prevent crashes related to the chain metadata
> chore: safe parse chain metadata buildMultiprovider

- src/features/deliveryStatus/useMessageDeliveryStatus.tsx
- src/features/messages/MessageTable.tsx
- src/features/messages/cards/WarpTransferDetailsCard.tsx
- src/features/messages/pi-queries/fetchPiChainMessages.test.ts
- src/features/messages/queries/fragments.ts
- src/features/messages/queries/parse.ts
- src/features/messages/utils.ts
- src/types.ts
fixes #199 
- Now shows warped token in the table row if it is a hyperlane warp route transfer
- Re-use `parseWarpRouteMessageDetails` for this and move to `utils`
- Move the `message_body`, `origin_tx_recipient` and `destination_tx_recipient` from `Message` to `MessageStub`, also match the parsing and typing for this
> feat: warped token row

- package.json
- src/features/messages/MessageTable.tsx
- src/features/messages/cards/WarpTransferDetailsCard.tsx
- src/features/messages/utils.ts
- src/types.ts
- yarn.lock
- Instead of having one variable for each needed value, refactor the parsing tokens into `originToken` and `destinationToken`, this will also be useful in a future PR to include token icons for the message table
- Upgrade registry verrsion
> chore: refactor message parsing and bump registry version

- next.config.js
- src/components/icons/TokenIcon.tsx
- src/consts/links.ts
- src/features/messages/MessageTable.tsx
- Update MessageTable and the warped token field to include a logo
- Add `TokenIcon` component
- Use the public CDN jsdelivr to get these images
- Update img-src permission to include jsdelivr image from the registry
> feat: add token logo to message table

- src/components/icons/TokenIcon.tsx
- src/features/messages/MessageTable.tsx
- src/features/messages/cards/WarpTransferDetailsCard.tsx
- Fix img size issue for token icon
- Improve warped token row positioning
- Remove tooltip for token row and use empty space instead
- Now will show token icon for Warp Transfer Detail image if logoURI it exists
> chore: improve styling for warped route token
